### ISSUE TITLE
windows告诉我fernflowerUI已停止运行 怎么办 反编译1.5的jar时出现的

### ISSUE THREAD

**Issue by 2439905184** [6168218c/FernflowerUI#10]
fernflower已停止工作 windows可以尝试修复您的信息 可以修复吗

**Comment by 2439905184** [comment]
minecraft1.5.2

**Comment by 6168218c** [comment]
能不能把你的Jar文件发给 sunyukai584595410@126.com
我再测试一下

**Comment by 6168218c** [comment]
你是否安装了JDK/JRE

**Comment by 6168218c** [comment]
对不起,这是一个bug,正在努力修复

**Comment by 6168218c** [comment]
已成功修复
![image](https://user-images.githubusercontent.com/32412793/50005213-8c85b780-ffe4-11e8-9973-7e1ab6535e3a.png)
将合并入3.4.2版本
