### ISSUE TITLE
There is something wrong  happened in version 3.4.2 when I opened jar  files

### ISSUE THREAD

**Issue by yizhang-0** [6168218c/FernflowerUI#13]
Using "File" menu to open a jar file , this application which version is 3.4.2  will exit   and restart  suddenly. Plese review this issus.

**Comment by 6168218c** [comment]
Thank you for reporting the issue.However, the problem *doesn't occur* on my computer.
Please describe the problem in detail,such as your system(e.g. Windows10) and your jre version
Please go to %UserProfile%\Appdata\Local\FernflowerUI and send me a screenshot of that.
The folder should be like this
![image](https://user-images.githubusercontent.com/32412793/59472207-42d13900-8e70-11e9-81ff-332804c3c5cf.png)


#### Thank you for your support.

**Comment by yizhang-0** [comment]
Runing enviroment :
1.os :windows10 64 bits
2.jre :1.6.0-45


Problem:
1.This application (V3.4.2) will  exit and restart .


Problem occured conditions :
1.Have decomplied a jar file successed .
2. Using "File" menu  to reopen  another  jar file .

Screensshots:


1: Fernflower jar file directory





2.Application  directory 



3. Problem Screenshoots














------------------ 原始邮件 ------------------
发件人: "Kevin"<notifications@github.com>;
发送时间: 2019年6月14日(星期五) 上午6:49
收件人: "6168218c/FernflowerUI"<FernflowerUI@noreply.github.com>;
抄送: "廉政"<337546141@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [6168218c/FernflowerUI] There is something wrong  happened inversion 3.4.2 when I opened jar  files (#13)




Thank you for reporting the issue.However, the problem doesn't occur on my computer.
 Please describe the problem in detail,such as your system(e.g. Windows10) and your jre version
 Please go to %UserProfile%\Appdata\Local\FernflowerUI and send me a screenshot of that.
 The folder should be like this
 
 
Thank you for your support.

**Comment by yizhang-0** [comment]
Thanks for reply. 
Runing enviroment :
1.os :windows10 64 bits
2.jre :1.6.0-45

Problem:
1.This application (V3.4.2) will  exit and restart .

Problem occured conditions :
1.Have decomplied a jar file successed .
2. Using "File" menu  to reopen  another  jar file .

![2019-06-14_094428](https://user-images.githubusercontent.com/51686490/59477763-35747880-8e89-11e9-856c-01d5f55c5ef6.png)

**Comment by 6168218c** [comment]
Sorry,Maybe I forgot whether I had fixed this because the code was written 3 months ago.
But this still doesn't happen on my machine.
Maybe you can try the binary file attached.
[FernFlowerUI3.4.2+.zip](https://github.com/6168218c/FernflowerUI/files/3289890/FernFlowerUI3.4.2%2B.zip)

**Comment by yizhang-0** [comment]
Yeah，the  application  contained  by "FernFlowerUI3.4.2+.zip" has no this issue  .Thanks!
