### ISSUE TITLE
English please!

### ISSUE THREAD

**Issue by gomin1d** [6168218c/FernflowerUI#3]
![image](https://user-images.githubusercontent.com/32991511/38582419-517a9eba-3d18-11e8-8ea7-0cbf9164070e.png)

WTF?? I do not understand, не понимаю, 不明白

**Comment by 6168218c** [comment]
Ok, thank you for your advice.
As you know , I'm a Chinese ,and I'm not so good at English.But I'm working on it, and if you want to use the feature , set your language as OEM , US ,please.
The English edition is coming soon.
P.S.:Please forget my grammar mistakes :p

**Comment by 6168218c** [comment]
Oops,I closed it by mistake

**Comment by 6168218c** [comment]
Maybe you can use the DLL edition , some features provided by mfc140u.dll are in English

**Comment by 6168218c** [comment]
Ok, Now I only changed the language of the menu into English.
I think you will understand(明白).

**Comment by 6168218c** [comment]
It seems that you didn't install the Java Runtime Environment.The program requires JRE to run properly,and if you choose the "OK" button , the program will open the website of Oracle(http://www.oracle.com/technetwork/java/javase/overview/index.html).
The code page of the program is Unicode , and the following will be shown in Chinese if the language of your Windows is Chinese.
And I'm still working on it......

**Comment by gomin1d** [comment]
@6168218c, I also do not know English well, but it's an international language :D

JRE is installed, but I still have a warning:  
![image](https://user-images.githubusercontent.com/32991511/39019842-5f9c42d8-4433-11e8-9464-0d63ded46fb5.png)  
![image](https://user-images.githubusercontent.com/32991511/39019844-64624d12-4433-11e8-8b97-b61ed91a4f91.png)

Wow, I clicked something and it worked:  
![image](https://user-images.githubusercontent.com/32991511/39019930-a95bcdf8-4433-11e8-84d3-9cbb4b0d873d.png)

**Comment by lokha** [comment]
There is not enough button "Cancel"  
![image](https://user-images.githubusercontent.com/32991511/39020009-05a744de-4434-11e8-97c5-df5f0304244b.png)

**Comment by gomin1d** [comment]
@6168218c I do not understand your language installation tips. it would be great if you added the language setting in the program  
I will wait :)

**Comment by 6168218c** [comment]
@lokha Ok,thank you for your support,and I will work on it :)

**Comment by funinfofiles** [comment]
#2

**Comment by funinfofiles** [comment]
#1

**Comment by funinfofiles** [comment]
#4

**Comment by 6168218c** [comment]
@lokha Okay , I ' ve added multi-language in the program.But for some reasons(I ' m too lazy),I didn't 
add the feature of selecting the language.But it will be shown in English if the language of your Windows is not Chinese.Maybe there will be some bugs,because I used the function in the list below.For more information, see MSDN.~~I won't say that I haven't tested it in non-Chinese systems yet~~~
```C++
LANGID GetSystemDefaultUILanguage(void);

BOOL SetProcessPreferredUILanguages(
  _In_      DWORD    dwFlags,
  _In_opt_  PCZZWSTR pwszLanguagesBuffer,
  _Out_opt_ PULONG   pulNumLanguages
);

LANGID SetThreadUILanguage(
  _In_ LANGID LangId
);

```

**Comment by 6168218c** [comment]
@lokha What do U think of this guy?
![fernflowerui_en](https://user-images.githubusercontent.com/32412793/39962698-b0dc3a00-5689-11e8-8092-ddf5ebc836b5.jpg)
Will come out in version 3.3 and later

**Comment by 6168218c** [comment]
Now it's fixed

**Comment by gomin1d** [comment]
@6168218c yes, it is fixed! Great job, I'm so glad. so glad there is a ui for fermflower
