### ISSUE TITLE
ERROR: Archive file or some parts of its content invalid: file.jar

### ISSUE THREAD

**Issue by gomin1d** [6168218c/FernflowerUI#7]
![image](https://user-images.githubusercontent.com/32991511/42035486-bb483332-7aeb-11e8-94a9-b8c25c767461.png)

**Comment by 6168218c** [comment]
Could you discribe the problom in detail, and you can send the jar file to me at **sunyukai584595410@126.com**
And I will check that if there is something wrong with it.
Thank you again for reporting issues.

**Comment by 6168218c** [comment]
And it works well on my PC as the image below
![issueforinvalidjar](https://user-images.githubusercontent.com/32412793/42419861-7ff202ac-82ef-11e8-9f28-39103581dc64.jpg)
Therefore, please send me your jar file at **sunyukai584595410@126.com**,and I will check that.

**Comment by 6168218c** [comment]
Or you can open your regedit.exe and delete the "FernflowerUI_MFC" item as the image below.

![issueforinvalidjar](https://user-images.githubusercontent.com/32412793/42419909-281907f0-82f0-11e8-996b-cabcea5c62c9.jpg)

Maybe this will work

**Comment by gomin1d** [comment]
@6168218c well, I will send all the information to you on the email

**Comment by 6168218c** [comment]
@lokha Now the issue is fixed in version 3.4.1,which may be released in August.(I'm working on other features in version 3.4.1)In version 3.4.1 and later , the program will use the [fernflower](https://github.com/JetBrains/intellij-community/tree/master/plugins/java-decompiler/engine) made by @JetBrains,and it can decompile your jar file correctly.

**Comment by gomin1d** [comment]
@6168218c it is great

**Comment by 6168218c** [comment]
@lokha Thank you again for reporting the issue,and thank you so much for your support:smile:.
