### ISSUE TITLE
An issue by Andy Y.

### ISSUE THREAD

**Issue by hzyangjc** [6168218c/FernflowerUI#9]
Hi 6168218c!
Going to change my blog's theme recently.
But no time :(

**Comment by 6168218c** [comment]
No problems about that.
Thank you a lot for creating the issue.
I don't have time,too :(
No time for coding,playing or something else

**Comment by hzyangjc** [comment]
social social
I'm at the school now:)

**Comment by hzyangjc** [comment]
the blog is developed just now.
[go and see](https://hzyangjc.github.io)
